site_name: Meeting Minutes & Agendas
docs_dir: meetings

theme:
  name: mkdocs
  custom_dir: overrides # Enables custom HTML template overrides
  font: false
  features:
    - navigation.prune
    - search.suggest
    - search.highlight
