site_name: Meeting Minutes & Agendas
docs_dir: docs

theme:
  name: mkdocs

plugins:
  - search
  - mkdocs-breadcrumbs-plugin:
      delimiter: ' / ' # separator between sections
      log_level: 'WARNING' # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        - 'docs/mkdocs/**'
        - 'docs/mkdocs' # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
      use_page_titles: true # use page title instead of path in breadcrumbs
      home_text: 'Home'

nav:
  - Home: index.md
  - Browse Archive: meetings
  - Search Portal: search.md
