site_name: Meeting Minutes & Agendas
docs_dir: docs

theme:
  name: mkdocs

plugins:
  - search
  - mkdocs-breadcrumbs-plugin:
      delimiter: ' > '
      use_page_titles: true

nav:
  - Home: index.md
  - Browse Archive: meetings
  - Search Portal: search.md
